config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
	# emailもカラム用意してあるけど、とりあえず使わない方針
	before_save do
		self.name = name.downcase
		self.email = email.downcase
	end
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
#	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
#	validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(name: params[:name].downcase)
		if user && user.authenticate(params[:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid name/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Poketool Hub"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header id="navbar">
	<div class= "site-box">
		<div class="container">
			<%= link_to "Poketool Hub", root_path, id: "logo" %>
			<ul class="nav-header">
				<li class="nav"><%= link_to "Home", root_path %></li>
				<li class="nav"><%= link_to "Help", '#' %></li>
				<li class="nav"><%= link_to "ポケモン図鑑", '#' %></li>
				<li class="nav"><%= link_to "ダメージ計算機", '#' %></li>
				<li><span class="dropmenu">
					<ul class="no-js">
					<li><%= link_to "その他 ▼", '#', class: "clicker" %>
						<ul>
							<li><%= link_to "個体値・ステータス判定", '#' %></li>
							<li><%= link_to "個体管理ツール", '#' %></li>
						</ul>
					</li></ul>
				</span></li>
			</ul>
			<span class="session-nav">
				<% if signed_in? %>
					<%= link_to "サインアウト", signout_path, method: "delete" %>
				<% else %>
				<% end %>
			</span>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  # IEのバージョンが9より前の場合html5simを使用
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', :debug => true, media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', :debug => true, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class= "site-box">
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<header id="navbar">
		<div class= "site-box">
			<div class="container">
				<%= link_to "Poketool Hub", root_path, id: "logo" %>
				<ul class="nav header">
					<li><%= link_to "Home", root_path, class: "nav" %></li>
					<li><%= link_to "Help", '#', class: "nav" %></li>
					<li><%= link_to "ポケモン図鑑", '#', class: "nav" %></li>
					<li><%= link_to "ダメージ計算機", '#', class: "nav" %></li>
					<li><ul class="dropmenu">
						<li><%= link_to "その他 ▼", '#', class: "nav" %>
							<ul>
								<li><%= link_to "個体値・ステータス判定", '#' %></li>
								<li><%= link_to "個体管理ツール", '#' %></li>
							</ul>
						</li>
					</ul></li>
				</ul>
			</div>
		</div>
	</header>

	<div class= "site-box">
		<div class="container">
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div id="row">
<!--	<aside id="span4">
	</aside>-->
	<div id="span8">
		<p><h1 class="center">Poketool Hubへようこそ！</h1></p>

		<h2>
			ポケモン育成・対戦に役立つ各種ツールを一括提供しようと頑張っているサイトです。<br>
			鋭意製作中。<span class="count "></span>
		</h2>
	</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>